### ISSUE TITLE
Last Active No Longer Accurate

### ISSUE THREAD

**Issue by swjurgens** [rlesniak/tind3r.com#1]
Last active stopped working and displays a date that is over 2 years ago. I noticed on Tinder Reddit someone had posted this:

I noticed while running one of my scripts that the web api was change to name the "ping_time" property "last_activity_date", so unless they bring back "ping_time" old versions of tinder won't display latest activity. Of course 3rd party app devs can just update their code.

Is this something you'll be able to get updated on Tind3r?

**Comment by rlesniak** [comment]
Key `ping_time` has fixed date to: `2014-12-09T00:00:00.000Z`. So what we can do is to have hope that they will bring it back to work.
