### ISSUE TITLE
Servers completely down

### ISSUE THREAD

**Issue by NewGitHubUser154** [rlesniak/tind3r.com#11]
Service isn't working at all this morning. Server ping has no response

**Comment by dstamos** [comment]
Extension removed from Chrome store and the github repo with that code is taken down.
Your site was much better than flamite's. 10/10 basically.
Would be nice if you could get around things and put everything back up under a different name or whatever. It took them almost a year to take your stuff down.

**Comment by theY4Kman** [comment]
:'(

**Comment by rlesniak** [comment]
Working now

**Comment by fredriksn** [comment]
Is there a way to download the chrome extension again?
