### ISSUE TITLE
FB OAuth unexpectedly strict about field names

### ISSUE THREAD

**Issue by airhadoken** [rlesniak/tind3r.com#21]
As of this morning, Facebook would not complete the tind3r OAuth popup, instead giving a "This page isn't available" message.  I did some digging and found that `api_key` in CONNECT_URL needs to be changed to `client_id` to complete the OAuth dialog.

**Comment by ghost** [comment]
Where in the code can I change that?

**Comment by airhadoken** [comment]
If you have v0.3.0 of the extension, it's line 1953 of background.bundle.js

**Comment by rlesniak** [comment]
Thx, updated
