### ISSUE TITLE
I can't run tind3r 

### ISSUE THREAD

**Issue by Aimost** [rlesniak/tind3r.com#7]
Hello, first of all thank you to the creator of this incredible tool. 

I have ideas that I want to add to the tind3r project such as filtering BIO searches of profiles.

I'm trying to run tind3r on my server but I can't understand what's going on...

> $ NODE_ENV=production PORT=3000 node server.js
> fs.js:663
>   return binding.open(pathModule.toNamespacedPath(path),
>                  ^
> 
> Error: ENOENT: no such file or directory, open '/home/user/www/dist/webpack-assets.json'
>     at Object.fs.openSync (fs.js:663:18)
>     at Object.fs.readFileSync (fs.js:568:33)
>     at Object.<anonymous> (/home/entaquill44/www/server.js:25:25)
>     at Module._compile (module.js:660:30)
>     at Object.Module._extensions..js (module.js:671:10)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>     at Function.Module.runMain (module.js:701:10)
>     at startup (bootstrap_node.js:193:16)
>     at bootstrap_node.js:617:3
> error Command failed with exit code 1.

yarn --version 0.27.5
npm -v 5.6.0

**Comment by rlesniak** [comment]
Thanks man! Fixed, feel free to contribute! 😃
